### ISSUE TITLE
Hello World Fails.

### ISSUE THREAD

**Issue by rdebath** [qpalzmqaz123/brainfuck#1]
This program should print "Hello World!"
Your interpreter's `-` command works very strangely, leaving any cell value in 128..255 unmodified. 

``` bf
+[>[<-[]>+[>+++>[+++++++++++>][>]-[<]>-]]++++++++++<]>
>>>>>----.<<+++.<-..+++.<-.>>>.<<.+++.------.>-.<<+.<.
```

**Comment by qpalzmqaz123** [comment]
I fixed it, thank you
